{
 "title": "Geth Server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Block",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth_block" }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_block_transactions", "legendFormat": "Transactions" }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth_eth_transfers" }
   ]
  },
  {
   "title": "Token Transfers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth_token_transfers" }
   ]
  },
  {
   "title": "ETH Value",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth_block_value" }
   ]
  },
  {
   "title": "ERC20 Token Transfers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_token_transfers", "legendFormat": "Token Transfers" }
   ]
  },
  {
   "title": "Since Last Block",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "geth_seconds_last_block" }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_eth_transfers", "legendFormat": "ETH Transfers" }
   ]
  },
  {
   "title": "Gas Price (gwei)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_gas_price / 1000000000", "legendFormat": "gwei" }
   ]
  },
  {
   "title": "Gas Price",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth_gas_price / 1000000000" }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth_pending_transactions" }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "geth_block_size_bytes", "legendFormat": "Token Transfers" }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_pending_transactions", "legendFormat": "Pending Transactions" }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_block_difficulty / 10000000000000",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_block_gas_used", "legendFormat": "Token Transfers" }
   ]
  },
  {
   "title": "Contracts Created",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "geth_contracts_created", "legendFormat": "Contracts" }
   ]
  },
  {
   "title": "Block Nonce",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_block_nonce / 1000000000000000000",
     "legendFormat": "Nonce"
    }
   ]
  },
  {
   "title": "Server Response",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "geth_load_time", "legendFormat": "Server Response" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "content": "<p align=\"center\" style=\"font-size:30pt\">Today Totals</p>"
  }
 ]
}